server:
  port: 8381
spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: USER-SERVICE
          uri: ${USER_SERVICE_URL:http://localhost:8382}
          predicates:
            - Path=/api/v1/user/**
          filters:
            - name: CircuitBreaker
              args:
                name: USER-SERVICE
                fallbackuri: forward:/userServiceFallback
        - id: NOTIFICATION-SERVICE
          uri: ${NOTIFICATION_SERVICE_URL:http://localhost:8383}
          predicates:
            - Path=/api/v1/notification/**
          filters:
            - name: CircuitBreaker
              args:
                name: NOTIFICATION-SERVICE
                fallbackuri: forward:/notificationServiceFallback

        - id: LEADS-SERVICE
          uri: ${LEADS_SERVICE_URL:http://localhost:8384}
          predicates:
            - Path=/api/v1/leads/**
          filters:
            - name: CircuitBreaker
              args:
                name: LEADS-SERVICE
                fallbackuri: forward:/leadsServiceFallback
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"


logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: DEBUG

microservices:
  user: ${USER_SERVICE_URL:http://localhost:8382/}+/api/v1/user

