server:
  port: 8381
spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: USER-SERVICE
          uri: ${USER_SERVICE_URL:http://localhost:8382}
          predicates:
            - Path=/api/v1/user/**
          filters:
            - name: CircuitBreaker
              args:
                name: USER-SERVICE
                fallbackuri: forward:/userServiceFallback
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"


logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: DEBUG

microservices:
  user: ${USER_SERVICE_URL:http://localhost:8382/}+/api/v1/user

